Crowd Simulator: GLWindow Class Reference
GLWindow Class Reference
Class in charge to handle the OpenGL Window and pass the user input to the CrowdEngine.
#include <GLWindow.h>
Public Slots
void toggleSimulation (bool _pressed)
void setDrawAxis (bool _pressed)
void setDrawCells (bool _pressed)
void setDrawBoundingBox (bool _pressed)
void setDrawCollisionRadius (bool _pressed)
void setDrawVelocityVector (bool _pressed)
void setDrawVisionRadius (bool _pressed)
void setDrawStrength (bool _pressed)
void setDrawStateColour (bool _pressed)
void setCurrentDummy (int _index)
void setShader (int _index)
void setFriction (double _friction)
void setGravity (double _gravity)
void rearrangeCellPartition (int _cellSize)
void loadBrains ()
void loadAgents ()
void restart ()
void clear ()
void scaleCollisionRadius (double _scale)
void scaleAxis (double _scale)
void setBoundingBoxSize (double _size)
void setPhysicsEngine (int _index)
Public Member Functions
GLWindow (QWidget *_parent)
Constructor for GLWindow.
~GLWindow ()
void setTimerInterval (int _interval)
Set the timer interval for updating the crowd engine.
void setWireframeMode (bool _wireframeMode)
Set the wireframe mode on.
void setStep (float _step)
Set the step for the simulation.
Protected Member Functions
void initializeGL ()
Initialize the OpenGL context.
void resizeGL (const int _w, const int _h)
Resize the Opengl window.
void paintGL ()
Render the current content of the OpenGL window.
Private Slots
void updateSimulation ()
void updateFPS ()
Private Member Functions
void buildBoidVAO ()
void loadMatricesToShader (ngl::TransformStack &_tx)
void drawCollisionCylinder (float _collisionRadius)
void drawCollisionSphere (float _mass, float _collisionRadius)
void drawVector (ngl::Vec4 _vector, float _scale)
void drawRadius (float _radius)
void drawStrength (float _strength, float _mass)
void setStateColour (std::string _state)
void mouseMoveEvent (QMouseEvent *_event)
void mousePressEvent (QMouseEvent *_event)
void mouseReleaseEvent (QMouseEvent *_event)
void wheelEvent (QWheelEvent *_event)
Private Attributes
QTimer * m_updateCrowdEngineTimer
The timer for updating the crowd engine.
QTimer * m_updateFPSTimer
The timer for checking the FPS of the system.
ngl::BBox * m_boundingBox
Bounding box that wraps the world to be drawn.
int m_groundSteps
Steps of the grip which represents the ground. This is calculated as boundingBoxSize / CellSize.
int m_fps
Current FPS of the system.
int m_frameCounter
Counter of the frames to calculate the FPS of the system each second.
ngl::Text * m_text
Text to render onto the screen.
bool m_rotate
To know if the user is currently rotating.
bool m_translate
To know if the user is currently translating.
std::pair< int, int > m_previousMousePosition
Stores the previous mouse position.
ngl::Vec2 m_globalRotation
Stores the global rotation.
ngl::Vec3 m_globalTranslation
Stores the global translation.
ngl::TransformStack m_transformStack
Transformation Stack which holds the transformations.
ngl::VAOPrimitives * m_primitives
Instance of ngl::VAOPrimitives to access to its functionalities.
ngl::ShaderLib * m_shader
Instance of ngl::ShaderLib to access to its functionalities.
int m_shaderIndex
Index of the current shader in use.
ngl::Camera m_camera
Stores the camera of the scene.
ngl::Light m_light
Stores the light of the scene.
std::map< std::string, ngl::Obj * > m_dummies
Vector which stores the VAO's of the dummies availables for representing the agents of the simulation.
ngl::Obj * m_currentDummy
Current dummy in use, in case it is no customized.
bool m_customDummy
To know if the customized dummy should be used or not.
ngl::VertexArrayObject * m_boidVAO
VAO of a simple boid.
float m_collisionRadiusScale
Remember the last collision radius scale used in case new agents are loaded.
bool m_drawBoundingBox
To know if the bounding box has to be drawn.
bool m_drawCollisionRadius
To know if the collision radius has to be drawn.
bool m_drawCells
To know if the cells have to be drawn.
bool m_drawVelocityVector
To know if the velocity vector has to be drawn.
bool m_drawVisionRadius
To know if the vision radius has to be drawn.
bool m_drawStrength
To know if the strength has to be drawn.
bool m_drawAxis
To know if the axis have to be drawn.
bool m_drawStateColour
To know if the state colour code has to be drawn.
float m_axisScale
The scale value of the axis in the origin.
bool m_wireframeMode
To know if the wireframe mode is active.
Parser * m_parser
The parser used to load agents.
CrowdEngine m_crowdEngine
The crowd engine used to perform the simulation.
Static Private Attributes
static const QString s_dummiesPath = "dummies"
Path for the dummies in the filesystem.
static const QString s_brainsPath = "brains"
Path for the brains in the filesystem.
static const QString s_agentsPath = "agents"
Path for the agents in the filesystem.
static const float s_rotationIncrement = 0.5
Rotation step when the user rotates with the mouse.
static const float s_translationIncrement = 0.05
Translation step when the user translates with the mouse.
static const float s_zoomIncrement = 1
Zoom step when the user makes zoom with the mouse wheel.
Detailed Description
Class in charge to handle the OpenGL Window and pass the user input to the CrowdEngine.
Definition at line 45 of file GLWindow.h.
Constructor & Destructor Documentation
GLWindow::GLWindow (QWidget * _parent)
Constructor for GLWindow.
Parameters
[in] parent the parent window to create the GL context in
in this ctor we need to call the CreateCoreGLContext class, this is mainly for the MacOS Lion version as we need to init the OpenGL 3.2 sub-system which is different than other platforms
Definition at line 24 of file GLWindow.cpp.
References m_axisScale, m_collisionRadiusScale, m_crowdEngine, m_customDummy, m_drawAxis, m_drawBoundingBox, m_drawCells, m_drawCollisionRadius, m_drawStateColour, m_drawStrength, m_drawVelocityVector, m_drawVisionRadius, m_fps, m_frameCounter, m_groundSteps, m_parser, m_previousMousePosition, m_rotate, m_translate, m_updateCrowdEngineTimer, m_updateFPSTimer, m_wireframeMode, CrowdEngine::setCellPartition(), CrowdEngine::setPhysicsEngine(), updateFPS(), and updateSimulation().
GLWindow::~GLWindow ()
Definition at line 80 of file GLWindow.cpp.
Member Function Documentation
void GLWindow::buildBoidVAO () private
Definition at line 269 of file GLWindow.cpp.
References m_boidVAO.
void GLWindow::clear () slot
Definition at line 955 of file GLWindow.cpp.
References CrowdEngine::clear(), m_crowdEngine, and m_updateCrowdEngineTimer.
void GLWindow::drawCollisionCylinder (float _collisionRadius) inline private
Definition at line 465 of file GLWindow.cpp.
References loadMatricesToShader(), m_primitives, m_transformStack, and m_wireframeMode.
void GLWindow::drawCollisionSphere (float _mass, float _collisionRadius) inline private
Definition at line 482 of file GLWindow.cpp.
References loadMatricesToShader(), m_primitives, m_transformStack, and m_wireframeMode.
void GLWindow::drawRadius (float _radius) inline private
Definition at line 549 of file GLWindow.cpp.
References loadMatricesToShader(), m_primitives, and m_transformStack.
void GLWindow::drawStrength (float _strength, float _mass) inline private
Definition at line 499 of file GLWindow.cpp.
References loadMatricesToShader(), m_primitives, and m_transformStack.
void GLWindow::drawVector (ngl::Vec4 _vector, float _scale) inline private
Definition at line 516 of file GLWindow.cpp.
References loadMatricesToShader(), m_primitives, and m_transformStack.
void GLWindow::initializeGL () protected
Initialize the OpenGL context.
Definition at line 87 of file GLWindow.cpp.
References buildBoidVAO(), m_boundingBox, m_camera, m_currentDummy, m_dummies, m_groundSteps, m_light, m_primitives, m_shader, m_shaderIndex, m_text, s_dummiesPath, and SHADER_PHONG.
void GLWindow::loadAgents () slot
Definition at line 933 of file GLWindow.cpp.
References CrowdEngine::addAgents(), Parser::loadAgents(), m_collisionRadiusScale, m_crowdEngine, m_dummies, m_parser, s_agentsPath, and CrowdEngine::scaleCollisionRadius().
void GLWindow::loadBrains () slot
Definition at line 922 of file GLWindow.cpp.
References CrowdEngine::loadBrain(), m_crowdEngine, and s_brainsPath.
void GLWindow::loadMatricesToShader (ngl::TransformStack & _tx) inline private
Definition at line 307 of file GLWindow.cpp.
References m_camera, m_shader, m_shaderIndex, SHADER_COLOUR, and SHADER_PHONG.
void GLWindow::mouseMoveEvent (QMouseEvent * _event) private
Definition at line 650 of file GLWindow.cpp.
References m_globalRotation, m_globalTranslation, m_previousMousePosition, m_rotate, m_transformStack, m_translate, s_rotationIncrement, and s_translationIncrement.
void GLWindow::mousePressEvent (QMouseEvent * _event) private
Definition at line 688 of file GLWindow.cpp.
References m_previousMousePosition, m_rotate, and m_translate.
void GLWindow::mouseReleaseEvent (QMouseEvent * _event) private
Definition at line 705 of file GLWindow.cpp.
References m_rotate, and m_translate.
void GLWindow::paintGL () protected
Render the current content of the OpenGL window.
The shader needs to be set each time because the ngl::text leaves nglTextShader
Definition at line 336 of file GLWindow.cpp.
References drawCollisionCylinder(), drawCollisionSphere(), drawRadius(), drawStrength(), drawVector(), CrowdEngine::getAgentsBegin(), CrowdEngine::getAgentsEnd(), CrowdEngine::getAgentsNumber(), CrowdEngine::getBoundingBoxSize(), CrowdEngine::getCellSize(), Agent::getCollisionRadius(), Agent::getDummy(), Agent::getMass(), CrowdEngine::getPEType(), Agent::getState(), Agent::getStrength(), Agent::getTransform(), Agent::getVelocity(), Agent::getVisionRadius(), loadMatricesToShader(), m_axisScale, m_boidVAO, m_boundingBox, m_crowdEngine, m_currentDummy, m_customDummy, m_drawAxis, m_drawBoundingBox, m_drawCells, m_drawCollisionRadius, m_drawStateColour, m_drawStrength, m_drawVelocityVector, m_drawVisionRadius, m_fps, m_primitives, m_shader, m_shaderIndex, m_text, m_transformStack, m_wireframeMode, PE_CYLINDER, PE_SPHERE, setStateColour(), SHADER_COLOUR, and SHADER_PHONG.
void GLWindow::rearrangeCellPartition (int _cellSize) slot
Definition at line 905 of file GLWindow.cpp.
References CrowdEngine::getBoundingBoxSize(), m_crowdEngine, m_groundSteps, m_primitives, m_updateCrowdEngineTimer, and CrowdEngine::rearrangePartition().
void GLWindow::resizeGL (const int _w, const int _h) protected
Resize the Opengl window.
Definition at line 299 of file GLWindow.cpp.
References m_camera, and m_text.
void GLWindow::restart () slot
Definition at line 970 of file GLWindow.cpp.
References m_crowdEngine, m_updateCrowdEngineTimer, and CrowdEngine::restart().
void GLWindow::scaleAxis (double _scale) slot
Definition at line 777 of file GLWindow.cpp.
References m_axisScale.
void GLWindow::scaleCollisionRadius (double _scale) slot
Definition at line 809 of file GLWindow.cpp.
References m_collisionRadiusScale, m_crowdEngine, and CrowdEngine::scaleCollisionRadius().
void GLWindow::setBoundingBoxSize (double _size) slot
Definition at line 795 of file GLWindow.cpp.
References CrowdEngine::getCellSize(), m_crowdEngine, m_groundSteps, m_primitives, and CrowdEngine::setBoundingBoxSize().
void GLWindow::setCurrentDummy (int _index) slot
If you try to set a dummy that was not loaded it will throw an exception
Definition at line 840 of file GLWindow.cpp.
References m_currentDummy, m_customDummy, and m_dummies.
void GLWindow::setDrawAxis (bool _pressed) slot
Definition at line 771 of file GLWindow.cpp.
References m_drawAxis.
void GLWindow::setDrawBoundingBox (bool _pressed) slot
Definition at line 789 of file GLWindow.cpp.
References m_drawBoundingBox.
void GLWindow::setDrawCells (bool _pressed) slot
Definition at line 783 of file GLWindow.cpp.
References m_drawCells.
void GLWindow::setDrawCollisionRadius (bool _pressed) slot
Definition at line 803 of file GLWindow.cpp.
References m_drawCollisionRadius.
void GLWindow::setDrawStateColour (bool _pressed) slot
Definition at line 834 of file GLWindow.cpp.
References m_drawStateColour.
void GLWindow::setDrawStrength (bool _pressed) slot
Definition at line 828 of file GLWindow.cpp.
References m_drawStrength.
void GLWindow::setDrawVelocityVector (bool _pressed) slot
Definition at line 816 of file GLWindow.cpp.
References m_drawVelocityVector.
void GLWindow::setDrawVisionRadius (bool _pressed) slot
Definition at line 822 of file GLWindow.cpp.
References m_drawVisionRadius.
void GLWindow::setFriction (double _friction) inline slot
Definition at line 275 of file GLWindow.h.
References m_crowdEngine, and CrowdEngine::setFriction().
void GLWindow::setGravity (double _gravity) inline slot
Definition at line 276 of file GLWindow.h.
References m_crowdEngine, and CrowdEngine::setGravity().
void GLWindow::setPhysicsEngine (int _index) slot
Definition at line 985 of file GLWindow.cpp.
References CrowdEngine::getBoundingBoxSize(), CrowdEngine::getPEType(), m_crowdEngine, PE_CYLINDER, PE_SPHERE, CrowdEngine::setBoundingBoxSize(), and CrowdEngine::setPhysicsEngine().
void GLWindow::setShader (int _index) slot
Definition at line 893 of file GLWindow.cpp.
References m_shaderIndex, SHADER_COLOUR, and SHADER_PHONG.
void GLWindow::setStateColour (std::string _state) inline private
Definition at line 560 of file GLWindow.cpp.
References m_shader.
void GLWindow::setStep (float _step) inline
Set the step for the simulation.
Definition at line 261 of file GLWindow.h.
References m_crowdEngine, and CrowdEngine::setStep().
void GLWindow::setTimerInterval (int _interval) inline
Set the timer interval for updating the crowd engine.
Definition at line 253 of file GLWindow.h.
References m_updateCrowdEngineTimer.
void GLWindow::setWireframeMode (bool _wireframeMode) inline
Set the wireframe mode on.
Definition at line 257 of file GLWindow.h.
References m_wireframeMode.
void GLWindow::toggleSimulation (bool _pressed) slot
Definition at line 750 of file GLWindow.cpp.
References m_updateCrowdEngineTimer.
void GLWindow::updateFPS () private slot
Definition at line 764 of file GLWindow.cpp.
References m_fps, and m_frameCounter.
void GLWindow::updateSimulation () private slot
Definition at line 743 of file GLWindow.cpp.
References m_crowdEngine, m_frameCounter, and CrowdEngine::update().
void GLWindow::wheelEvent (QWheelEvent * _event) private
Definition at line 717 of file GLWindow.cpp.
References m_globalRotation, m_globalTranslation, m_transformStack, and s_zoomIncrement.
Member Data Documentation
float GLWindow::m_axisScale private
The scale value of the axis in the origin.
Definition at line 208 of file GLWindow.h.
ngl::VertexArrayObject* GLWindow::m_boidVAO private
VAO of a simple boid.
Definition at line 167 of file GLWindow.h.
ngl::BBox* GLWindow::m_boundingBox private
Bounding box that wraps the world to be drawn.
Definition at line 88 of file GLWindow.h.
ngl::Camera GLWindow::m_camera private
Stores the camera of the scene.
Definition at line 146 of file GLWindow.h.
float GLWindow::m_collisionRadiusScale private
Remember the last collision radius scale used in case new agents are loaded.
Definition at line 172 of file GLWindow.h.
CrowdEngine GLWindow::m_crowdEngine private
The crowd engine used to perform the simulation.
Definition at line 221 of file GLWindow.h.
ngl::Obj* GLWindow::m_currentDummy private
Current dummy in use, in case it is no customized.
Definition at line 159 of file GLWindow.h.
bool GLWindow::m_customDummy private
To know if the customized dummy should be used or not.
Definition at line 163 of file GLWindow.h.
bool GLWindow::m_drawAxis private
To know if the axis have to be drawn.
Definition at line 200 of file GLWindow.h.
bool GLWindow::m_drawBoundingBox private
To know if the bounding box has to be drawn.
Definition at line 176 of file GLWindow.h.
bool GLWindow::m_drawCells private
To know if the cells have to be drawn.
Definition at line 184 of file GLWindow.h.
bool GLWindow::m_drawCollisionRadius private
To know if the collision radius has to be drawn.
Definition at line 180 of file GLWindow.h.
bool GLWindow::m_drawStateColour private
To know if the state colour code has to be drawn.
Definition at line 204 of file GLWindow.h.
bool GLWindow::m_drawStrength private
To know if the strength has to be drawn.
Definition at line 196 of file GLWindow.h.
bool GLWindow::m_drawVelocityVector private
To know if the velocity vector has to be drawn.
Definition at line 188 of file GLWindow.h.
bool GLWindow::m_drawVisionRadius private
To know if the vision radius has to be drawn.
Definition at line 192 of file GLWindow.h.
std::map<std::string,ngl::Obj*> GLWindow::m_dummies private
Vector which stores the VAO's of the dummies availables for representing the agents of the simulation.
Definition at line 155 of file GLWindow.h.
int GLWindow::m_fps private
Current FPS of the system.
Definition at line 97 of file GLWindow.h.
int GLWindow::m_frameCounter private
Counter of the frames to calculate the FPS of the system each second.
Definition at line 102 of file GLWindow.h.
ngl::Vec2 GLWindow::m_globalRotation private
Stores the global rotation.
Definition at line 122 of file GLWindow.h.
ngl::Vec3 GLWindow::m_globalTranslation private
Stores the global translation.
Definition at line 126 of file GLWindow.h.
int GLWindow::m_groundSteps private
Steps of the grip which represents the ground. This is calculated as boundingBoxSize / CellSize.
Definition at line 93 of file GLWindow.h.
ngl::Light GLWindow::m_light private
Stores the light of the scene.
Definition at line 150 of file GLWindow.h.
Parser* GLWindow::m_parser private
The parser used to load agents.
Definition at line 217 of file GLWindow.h.
std::pair<int,int> GLWindow::m_previousMousePosition private
Stores the previous mouse position.
Definition at line 118 of file GLWindow.h.
ngl::VAOPrimitives* GLWindow::m_primitives private
Instance of ngl::VAOPrimitives to access to its functionalities.
Definition at line 134 of file GLWindow.h.
bool GLWindow::m_rotate private
To know if the user is currently rotating.
Definition at line 110 of file GLWindow.h.
ngl::ShaderLib* GLWindow::m_shader private
Instance of ngl::ShaderLib to access to its functionalities.
Definition at line 138 of file GLWindow.h.
int GLWindow::m_shaderIndex private
Index of the current shader in use.
Definition at line 142 of file GLWindow.h.
ngl::Text* GLWindow::m_text private
Text to render onto the screen.
Definition at line 106 of file GLWindow.h.
ngl::TransformStack GLWindow::m_transformStack private
Transformation Stack which holds the transformations.
Definition at line 130 of file GLWindow.h.
bool GLWindow::m_translate private
To know if the user is currently translating.
Definition at line 114 of file GLWindow.h.
QTimer* GLWindow::m_updateCrowdEngineTimer private
The timer for updating the crowd engine.
Definition at line 80 of file GLWindow.h.
QTimer* GLWindow::m_updateFPSTimer private
The timer for checking the FPS of the system.
Definition at line 84 of file GLWindow.h.
bool GLWindow::m_wireframeMode private
To know if the wireframe mode is active.
Definition at line 212 of file GLWindow.h.
const QString GLWindow::s_agentsPath = "agents" static private
Path for the agents in the filesystem.
Definition at line 63 of file GLWindow.h.
const QString GLWindow::s_brainsPath = "brains" static private
Path for the brains in the filesystem.
Definition at line 59 of file GLWindow.h.
const QString GLWindow::s_dummiesPath = "dummies" static private
Path for the dummies in the filesystem.
Definition at line 55 of file GLWindow.h.
const float GLWindow::s_rotationIncrement = 0.5 static private
Rotation step when the user rotates with the mouse.
Definition at line 67 of file GLWindow.h.
const float GLWindow::s_translationIncrement = 0.05 static private
Translation step when the user translates with the mouse.
Definition at line 71 of file GLWindow.h.
const float GLWindow::s_zoomIncrement = 1 static private
Zoom step when the user makes zoom with the mouse wheel.
Definition at line 75 of file GLWindow.h.
The documentation for this class was generated from the following files:
GLWindow.h
GLWindow.cpp