Crowd Simulator: CrowdEngine Class Reference
CrowdEngine Class Reference
This is the core class of the application. It is the abstract virtual world; it stores the agents and take care of all the updates.
#include <CrowdEngine.h>
Public Member Functions
CrowdEngine ()
~CrowdEngine ()
void setCellPartition (CellPartition *_cellPartition)
void setPhysicsEngine (PhysicsEngine *_physicsEngine)
void setStep (float _step)
void setFriction (float _friction)
void setGravity (float _gravity)
std::vector< Agent * >
::const_iterator getAgentsBegin ()
std::vector< Agent * >
::const_iterator getAgentsEnd ()
float getBoundingBoxSize () const
int getCellSize () const
physicsEngineType getPEType () const
int getAgentsNumber () const
void loadBrain (std::string _brain)
Brings a brain (lua function) to the memory.
void addAgent (Agent *_agent)
Add _agent to the world.
void addAgents (const std::vector< Agent * > &_agents)
Add _agents to the world.
void printAgents ()
Print information about the agents in the world.
void printCellPartition ()
Print information about the cell partition.
void rearrangePartition (int _cellSize)
Reconfigure the cell partition with a different size of cell.
void update ()
Update the world.
void clear ()
Remove all the current agents in the world.
void restart ()
Load the initial state of the agents in the world.
void scaleCollisionRadius (float _scale)
Multiply the collision radius of all the agents by _scale.
void setBoundingBoxSize (float _boundingBoxSize)
Adjust the size of the bounding box.
Private Attributes
std::vector< Agent * > m_agents
All the agents in the world.
std::vector< Agent * > m_initialAgents
A copy of the agents in their initial states needed for the reset of the system.
CellPartition * m_cellPartition
A reference to the cell partition in current use.
PhysicsEngine * m_physicsEngine
A reference to the physics engine in current use.
Static Private Attributes
static const std::string s_brainsPath
The path where the brains can be found in the filesystem.
static std::set< std::string > s_loadedBrains
A set that takes account about all the brains already loaded.
static lua_State * s_luaState
A reference to the lua state.
Detailed Description
This is the core class of the application. It is the abstract virtual world; it stores the agents and take care of all the updates.
Definition at line 22 of file CrowdEngine.h.
Constructor & Destructor Documentation
CrowdEngine::CrowdEngine ()
Definition at line 8 of file CrowdEngine.cpp.
References s_luaState, Agent::setLuaState(), and Agent::setStep().
CrowdEngine::~CrowdEngine ()
Definition at line 17 of file CrowdEngine.cpp.
References m_agents, and s_luaState.
Member Function Documentation
void CrowdEngine::addAgent (Agent * _agent)
Add _agent to the world.
Definition at line 49 of file CrowdEngine.cpp.
References CellPartition::addAgent(), Agent::getAgentID(), Agent::getBrain(), m_agents, m_cellPartition, m_initialAgents, and s_loadedBrains.
void CrowdEngine::addAgents (const std::vector< Agent * > & _agents)
Add _agents to the world.
Definition at line 66 of file CrowdEngine.cpp.
References addAgent().
void CrowdEngine::clear ()
Remove all the current agents in the world.
Definition at line 135 of file CrowdEngine.cpp.
References CellPartition::clear(), m_agents, m_cellPartition, and m_initialAgents.
std::vector<Agent*>::const_iterator CrowdEngine::getAgentsBegin () inline
Definition at line 67 of file CrowdEngine.h.
References m_agents.
std::vector<Agent*>::const_iterator CrowdEngine::getAgentsEnd () inline
Definition at line 68 of file CrowdEngine.h.
References m_agents.
int CrowdEngine::getAgentsNumber () const inline
Definition at line 72 of file CrowdEngine.h.
References m_agents.
float CrowdEngine::getBoundingBoxSize () const inline
Definition at line 69 of file CrowdEngine.h.
References PhysicsEngine::getBoundingBoxSize(), and m_physicsEngine.
int CrowdEngine::getCellSize () const inline
Definition at line 70 of file CrowdEngine.h.
References CellPartition::getCellSize(), and m_cellPartition.
physicsEngineType CrowdEngine::getPEType () const inline
Definition at line 71 of file CrowdEngine.h.
References PhysicsEngine::getType(), and m_physicsEngine.
void CrowdEngine::loadBrain (std::string _brain)
Brings a brain (lua function) to the memory.
Definition at line 30 of file CrowdEngine.cpp.
References s_loadedBrains, and s_luaState.
void CrowdEngine::printAgents ()
Print information about the agents in the world.
Definition at line 76 of file CrowdEngine.cpp.
References m_agents.
void CrowdEngine::printCellPartition () inline
Print information about the cell partition.
Definition at line 93 of file CrowdEngine.h.
References m_cellPartition, and CellPartition::printCells().
void CrowdEngine::rearrangePartition (int _cellSize) inline
Reconfigure the cell partition with a different size of cell.
Definition at line 97 of file CrowdEngine.h.
References m_agents, m_cellPartition, and CellPartition::rearrangePartition().
void CrowdEngine::restart ()
Load the initial state of the agents in the world.
Definition at line 142 of file CrowdEngine.cpp.
References CellPartition::addAgents(), CellPartition::clear(), m_agents, m_cellPartition, and m_initialAgents.
void CrowdEngine::scaleCollisionRadius (float _scale)
Multiply the collision radius of all the agents by _scale.
Definition at line 163 of file CrowdEngine.cpp.
References m_agents, and m_initialAgents.
void CrowdEngine::setBoundingBoxSize (float _boundingBoxSize) inline
Adjust the size of the bounding box.
Definition at line 117 of file CrowdEngine.h.
References m_physicsEngine, and PhysicsEngine::setBoundingBoxSize().
void CrowdEngine::setCellPartition (CellPartition * _cellPartition) inline
Definition at line 61 of file CrowdEngine.h.
References m_cellPartition.
void CrowdEngine::setFriction (float _friction) inline
Definition at line 64 of file CrowdEngine.h.
References m_physicsEngine, and PhysicsEngine::setFriction().
void CrowdEngine::setGravity (float _gravity) inline
Definition at line 65 of file CrowdEngine.h.
References m_physicsEngine, and PhysicsEngine::setGravity().
void CrowdEngine::setPhysicsEngine (PhysicsEngine * _physicsEngine) inline
Definition at line 62 of file CrowdEngine.h.
References m_physicsEngine.
void CrowdEngine::setStep (float _step) inline
Definition at line 63 of file CrowdEngine.h.
References Agent::setStep().
void CrowdEngine::update ()
Update the world.
Definition at line 85 of file CrowdEngine.cpp.
References PhysicsEngine::applyFriction(), PhysicsEngine::applyGravity(), PhysicsEngine::checkCollision(), PhysicsEngine::checkCollisionBoundingBox(), PhysicsEngine::checkCollisionGround(), m_agents, m_cellPartition, m_physicsEngine, CellPartition::updateCells(), and CellPartition::updateNeighbours().
Member Data Documentation
std::vector<Agent*> CrowdEngine::m_agents private
All the agents in the world.
Definition at line 42 of file CrowdEngine.h.
CellPartition* CrowdEngine::m_cellPartition private
A reference to the cell partition in current use.
Definition at line 51 of file CrowdEngine.h.
std::vector<Agent*> CrowdEngine::m_initialAgents private
A copy of the agents in their initial states needed for the reset of the system.
Definition at line 47 of file CrowdEngine.h.
PhysicsEngine* CrowdEngine::m_physicsEngine private
A reference to the physics engine in current use.
Definition at line 55 of file CrowdEngine.h.
const std::string CrowdEngine::s_brainsPath static private
The path where the brains can be found in the filesystem.
Definition at line 29 of file CrowdEngine.h.
std::set< std::string > CrowdEngine::s_loadedBrains static private
A set that takes account about all the brains already loaded.
Definition at line 33 of file CrowdEngine.h.
lua_State * CrowdEngine::s_luaState static private
A reference to the lua state.
Definition at line 37 of file CrowdEngine.h.
The documentation for this class was generated from the following files:
CrowdEngine.h
CrowdEngine.cpp