Crowd Simulator: CylinderPE Class Reference
CylinderPE Class Reference
Specialized cylinder-based PhysicsEngine.
#include <CylinderPE.h>
Public Member Functions
CylinderPE ()
void checkCollision (Agent *_a1, Agent *_a2)
Check if there exists collision between two agents and fix their positions and velocities.
Public Member Functions inherited from PhysicsEngine
PhysicsEngine (physicsEngineType _type)
void setBoundingBoxSize (float _boxSize)
void setFriction (float _friction)
void setGravity (float _gravity)
float getBoundingBoxSize () const
physicsEngineType getType () const
void checkCollisionBoundingBox (Agent *_agent)
Check collision with box that wraps the world.
void checkCollisionGround (Agent *_agent)
Check collision with the ground.
void applyFriction (Agent *_agent)
Apply friction force on _agent.
void applyGravity (Agent *_agent)
Apply gravity force on _agent.
Additional Inherited Members
Static Protected Attributes inherited from PhysicsEngine
static const float s_epsilon = 1E-10
Value used in the comparison of floats.
Detailed Description
Specialized cylinder-based PhysicsEngine.
Definition at line 15 of file CylinderPE.h.
Constructor & Destructor Documentation
CylinderPE::CylinderPE () inline
Definition at line 19 of file CylinderPE.h.
Member Function Documentation
void CylinderPE::checkCollision (Agent * _a1, Agent * _a2) virtual
Check if there exists collision between two agents and fix their positions and velocities.
Implements PhysicsEngine.
Definition at line 3 of file CylinderPE.cpp.
References Agent::distance(), Agent::getAgentID(), Agent::getCollisionRadius(), Agent::getPosition(), Agent::getPreviousPos(), Agent::getStep(), Agent::getVelocity(), PhysicsEngine::s_epsilon, Agent::setPosition(), and Agent::setVelocity().
The documentation for this class was generated from the following files:
CylinderPE.h
CylinderPE.cpp