Crowd Simulator: PhysicsEngine Class Reference
PhysicsEngine Class Reference abstract
This abstract class represents the interface of a physics engine, which is the responsible of handle the physics of the world, such as external forces or collisions.
#include <PhysicsEngine.h>
Public Member Functions
PhysicsEngine (physicsEngineType _type)
void setBoundingBoxSize (float _boxSize)
void setFriction (float _friction)
void setGravity (float _gravity)
float getBoundingBoxSize () const
physicsEngineType getType () const
virtual void checkCollision (Agent *_a1, Agent *_a2)=0
Check if there exists collision between two agents and fix their positions and velocities.
void checkCollisionBoundingBox (Agent *_agent)
Check collision with box that wraps the world.
void checkCollisionGround (Agent *_agent)
Check collision with the ground.
void applyFriction (Agent *_agent)
Apply friction force on _agent.
void applyGravity (Agent *_agent)
Apply gravity force on _agent.
Static Protected Attributes
static const float s_epsilon = 1E-10
Value used in the comparison of floats.
Private Attributes
physicsEngineType m_type
Type of the physics engine.
float m_boundingBoxSize
Size of the box which wraps the world.
float m_friction
Magnitude of the friction force.
float m_gravity
Magnitude of the gravity force.
Detailed Description
This abstract class represents the interface of a physics engine, which is the responsible of handle the physics of the world, such as external forces or collisions.
Definition at line 30 of file PhysicsEngine.h.
Constructor & Destructor Documentation
PhysicsEngine::PhysicsEngine (physicsEngineType _type)
Definition at line 5 of file PhysicsEngine.cpp.
References m_boundingBoxSize, m_friction, m_gravity, and m_type.
Member Function Documentation
void PhysicsEngine::applyFriction (Agent * _agent)
Apply friction force on _agent.
Definition at line 39 of file PhysicsEngine.cpp.
References Agent::applyForce(), Agent::getVelocity(), and m_friction.
void PhysicsEngine::applyGravity (Agent * _agent)
Apply gravity force on _agent.
Definition at line 62 of file PhysicsEngine.cpp.
References Agent::applyForce(), and m_gravity.
virtual void PhysicsEngine::checkCollision (Agent * _a1, Agent * _a2) pure virtual
Check if there exists collision between two agents and fix their positions and velocities.
Implemented in CylinderPE, and SpherePE.
void PhysicsEngine::checkCollisionBoundingBox (Agent * _agent)
Check collision with box that wraps the world.
Definition at line 13 of file PhysicsEngine.cpp.
References Agent::getPosition(), Agent::getPreviousPos(), Agent::getStep(), Agent::getVelocity(), m_boundingBoxSize, Agent::setPosition(), and Agent::setVelocity().
void PhysicsEngine::checkCollisionGround (Agent * _agent)
Check collision with the ground.
Definition at line 44 of file PhysicsEngine.cpp.
References Agent::getPosition(), Agent::getVelocity(), Agent::setPosition(), and Agent::setVelocity().
float PhysicsEngine::getBoundingBoxSize () const inline
Definition at line 64 of file PhysicsEngine.h.
References m_boundingBoxSize.
physicsEngineType PhysicsEngine::getType () const inline
Definition at line 65 of file PhysicsEngine.h.
References m_type.
void PhysicsEngine::setBoundingBoxSize (float _boxSize) inline
Definition at line 60 of file PhysicsEngine.h.
References m_boundingBoxSize.
void PhysicsEngine::setFriction (float _friction) inline
Definition at line 61 of file PhysicsEngine.h.
References m_friction.
void PhysicsEngine::setGravity (float _gravity) inline
Definition at line 62 of file PhysicsEngine.h.
References m_gravity.
Member Data Documentation
float PhysicsEngine::m_boundingBoxSize private
Size of the box which wraps the world.
Definition at line 41 of file PhysicsEngine.h.
float PhysicsEngine::m_friction private
Magnitude of the friction force.
Definition at line 45 of file PhysicsEngine.h.
float PhysicsEngine::m_gravity private
Magnitude of the gravity force.
Definition at line 49 of file PhysicsEngine.h.
physicsEngineType PhysicsEngine::m_type private
Type of the physics engine.
Definition at line 37 of file PhysicsEngine.h.
const float PhysicsEngine::s_epsilon = 1E-10 static protected
Value used in the comparison of floats.
Definition at line 55 of file PhysicsEngine.h.
The documentation for this class was generated from the following files:
PhysicsEngine.h
PhysicsEngine.cpp