#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include "GLWindow.h"

/*
 * This is the MainWindow Class which is generated by the Ui file,
 * if we wish to add anything to the main Ui we add it here
 */
class MainWindow : public QMainWindow
{

Q_OBJECT

private:
    GLWindow *m_gl;

private slots :
    /* Here we add our GLWindow extending the base functionality of our class*/

protected :
    /*Overwritten methods from QObject*/
    void keyPressEvent(QKeyEvent *_event);
    void resizeEvent (QResizeEvent * _event);

public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

};

#endif // MAINWINDOW_H
