Crowd Simulator: Agent Class Reference
Agent Class Reference
This class implements the body of the agent, which includes all the physical properties, neighbourhood, messages, transformation, etc. and knows about the brain, a lua function which is called every time an update occurs.
#include <Agent.h>
Public Member Functions
Agent ()
Agent (ngl::Vec4 _pos, std::string _flock, std::string _brain)
Agent (const Agent &_agent)
~Agent ()
void setMass (float _mass)
void setMaxStrength (float _maxStrength)
void setMaxSpeed (float _maxSpeed)
void setHeading (ngl::Vec4 _heading)
void setVisionRadius (float _visionRadius)
void setPosition (ngl::Vec4 _pos)
void setPreviousPos (ngl::Vec4 _pos)
void setVelocity (ngl::Vec4 _vel)
void setNeighbours (const std::vector< Agent * > &_neighbours)
void setBrain (std::string _brain)
void setState (std::string _state)
void setDummy (ngl::Obj *_dummy)
void addAttribute (std::string _key, std::string _value)
float getAgentID () const
ngl::Vec4 getPosition () const
ngl::Vec4 getPreviousPos () const
float getMass () const
float getStrength () const
float getMaxStrength () const
ngl::Vec4 getVelocity () const
float getMaxSpeed () const
std::string getState () const
ngl::Transformation getTransform () const
int getVisionRadius () const
std::string getBrain () const
std::map< std::string,
std::string > getAttributes () const
float getCollisionRadius () const
std::vector< Agent * > getNeighbours () const
ngl::Vec4 getHeading () const
ngl::Obj * getDummy () const
void execute ()
Executes and therefore updates the state of the agent. This is where the routine of the brain is called.
void applyForce (ngl::Vec4 _force)
Requests to apply a force on this agent.
void sendMessage (message _message)
Sends a message to this agent.
float distance (const Agent *_agent) const
Calculates the distance with _agent.
void scaleCollisionRadius (float _scale)
Multiply the collision radius by _scale.
void print () const
print in the standard output information about the agent
Static Public Member Functions
static void setLuaState (lua_State *_luaState)
static void setStep (float _step)
static float getStep ()
Private Attributes
int m_agentID
The unique agent ID which differentiates it from any other.
float m_mass
The mass of the agent.
float m_strength
The current strength of the agent. This attribute is mutable.
float m_maxStrength
The maximum strength the agent has in full recovery state.
float m_visionRadius
This determines the portion of the world the agent is aware of.
ngl::Vec4 m_totalForce
Stores the total force applied on this agent.
ngl::Vec4 m_velocity
Current velocity of the agent.
ngl::Vec4 m_heading
Current heading of the agent. It often points the same direction than the velocity, but this does not have to happen always.
float m_maxSpeed
Maximum speed this agent can move with.
ngl::Transformation m_transformation
Current transformation of the agent. This includes translation rotation and scale.
ngl::Transformation m_previousTransform
Transformation of the agent in the previous tick.
std::string m_state
State of the agent. Information needed for the brain in order to take decisions.
std::string m_brain
Name of the brain, which correspondes with the lua function that encapsulates the "intelligent" routine.
std::vector< message > m_inbox
Vector with all the incoming messages from other agents.
std::map< std::string,
std::string > m_attributes
Map which stores extra attributes to provide more information to the brain.
std::vector< Agent * > m_neighbours
Vector with the current neighbours of the agent.
float m_collisionRadius
Radius of the agent in order to handle the collisions.
ngl::Obj * m_dummy
Dummy used when drawing the agent.
Static Private Attributes
static lua_State * s_luaState
Lua state which holds the scripted brain functions.
static int s_numberOfAgents = 0
Number of the current agents, used to associate an agent identifier.
static float s_step = 0.05
This controls the rate of change of the position of the agent. This attribute is very important and influences the simulation very much.
Detailed Description
This class implements the body of the agent, which includes all the physical properties, neighbourhood, messages, transformation, etc. and knows about the brain, a lua function which is called every time an update occurs.
Definition at line 46 of file Agent.h.
Constructor & Destructor Documentation
Agent::Agent ()
Definition at line 10 of file Agent.cpp.
References m_agentID, m_brain, m_collisionRadius, m_dummy, m_mass, m_maxSpeed, m_maxStrength, m_previousTransform, m_state, m_strength, m_transformation, m_visionRadius, and s_numberOfAgents.
Agent::Agent (ngl::Vec4 _pos, std::string _flock, std::string _brain)
Definition at line 27 of file Agent.cpp.
References m_agentID, m_attributes, m_brain, m_collisionRadius, m_dummy, m_mass, m_maxSpeed, m_maxStrength, m_previousTransform, m_state, m_strength, m_transformation, m_visionRadius, and s_numberOfAgents.
Agent::Agent (const Agent & _agent)
Definition at line 45 of file Agent.cpp.
References getAgentID(), getAttributes(), getBrain(), getCollisionRadius(), getDummy(), getHeading(), getMass(), getMaxSpeed(), getMaxStrength(), getPosition(), getState(), getTransform(), getVisionRadius(), m_agentID, m_attributes, m_brain, m_collisionRadius, m_dummy, m_heading, m_mass, m_maxSpeed, m_maxStrength, m_previousTransform, m_state, m_strength, m_transformation, and m_visionRadius.
Agent::~Agent () inline
Definition at line 148 of file Agent.h.
Member Function Documentation
void Agent::addAttribute (std::string _key, std::string _value) inline
Definition at line 167 of file Agent.h.
References m_attributes.
void Agent::applyForce (ngl::Vec4 _force) inline
Requests to apply a force on this agent.
Definition at line 195 of file Agent.h.
References m_totalForce.
float Agent::distance (const Agent * _agent) const
Calculates the distance with _agent.
Definition at line 126 of file Agent.cpp.
References getPosition(), and m_transformation.
void Agent::execute ()
Executes and therefore updates the state of the agent. This is where the routine of the brain is called.
Definition at line 152 of file Agent.cpp.
References message::agentID, getAgentID(), getAttributes(), getMass(), getPosition(), getState(), getStrength(), getVelocity(), message::label, m_agentID, m_attributes, m_brain, m_heading, m_inbox, m_mass, m_maxSpeed, m_maxStrength, m_neighbours, m_previousTransform, m_state, m_strength, m_totalForce, m_transformation, m_velocity, message::position, s_luaState, s_step, and message::strength.
float Agent::getAgentID () const inline
Definition at line 169 of file Agent.h.
References m_agentID.
std::map<std::string,std::string> Agent::getAttributes () const inline
Definition at line 181 of file Agent.h.
References m_attributes.
std::string Agent::getBrain () const inline
Definition at line 180 of file Agent.h.
References m_brain.
float Agent::getCollisionRadius () const inline
Definition at line 182 of file Agent.h.
References m_collisionRadius.
ngl::Obj* Agent::getDummy () const inline
Definition at line 185 of file Agent.h.
References m_dummy.
ngl::Vec4 Agent::getHeading () const inline
Definition at line 184 of file Agent.h.
References m_heading.
float Agent::getMass () const inline
Definition at line 172 of file Agent.h.
References m_mass.
float Agent::getMaxSpeed () const inline
Definition at line 176 of file Agent.h.
References m_maxSpeed.
float Agent::getMaxStrength () const inline
Definition at line 174 of file Agent.h.
References m_maxStrength.
std::vector<Agent*> Agent::getNeighbours () const inline
Definition at line 183 of file Agent.h.
References m_neighbours.
ngl::Vec4 Agent::getPosition () const inline
Definition at line 170 of file Agent.h.
References m_transformation.
ngl::Vec4 Agent::getPreviousPos () const inline
Definition at line 171 of file Agent.h.
References m_previousTransform.
std::string Agent::getState () const inline
Definition at line 177 of file Agent.h.
References m_state.
static float Agent::getStep () inline static
Definition at line 153 of file Agent.h.
References s_step.
float Agent::getStrength () const inline
Definition at line 173 of file Agent.h.
References m_strength.
ngl::Transformation Agent::getTransform () const inline
Definition at line 178 of file Agent.h.
References m_transformation.
ngl::Vec4 Agent::getVelocity () const inline
Definition at line 175 of file Agent.h.
References m_velocity.
int Agent::getVisionRadius () const inline
Definition at line 179 of file Agent.h.
References m_visionRadius.
void Agent::print () const
print in the standard output information about the agent
Definition at line 72 of file Agent.cpp.
References message::agentID, getAgentID(), getPosition(), message::label, m_agentID, m_attributes, m_brain, m_heading, m_inbox, m_mass, m_maxSpeed, m_maxStrength, m_neighbours, m_state, m_strength, m_totalForce, m_transformation, m_velocity, m_visionRadius, message::position, and message::strength.
void Agent::scaleCollisionRadius (float _scale) inline
Multiply the collision radius by _scale.
Definition at line 207 of file Agent.h.
References m_collisionRadius, and m_mass.
void Agent::sendMessage (message _message) inline
Sends a message to this agent.
Definition at line 199 of file Agent.h.
References m_inbox.
void Agent::setBrain (std::string _brain) inline
Definition at line 164 of file Agent.h.
References m_brain.
void Agent::setDummy (ngl::Obj * _dummy) inline
Definition at line 166 of file Agent.h.
References m_dummy.
void Agent::setHeading (ngl::Vec4 _heading)
Definition at line 131 of file Agent.cpp.
References m_heading, and m_transformation.
static void Agent::setLuaState (lua_State * _luaState) inline static
Definition at line 150 of file Agent.h.
References s_luaState.
void Agent::setMass (float _mass)
Definition at line 65 of file Agent.cpp.
References m_collisionRadius, m_mass, and m_transformation.
void Agent::setMaxSpeed (float _maxSpeed) inline
Definition at line 157 of file Agent.h.
References m_maxSpeed.
void Agent::setMaxStrength (float _maxStrength) inline
Definition at line 156 of file Agent.h.
References m_maxStrength, and m_strength.
void Agent::setNeighbours (const std::vector< Agent * > & _neighbours) inline
Definition at line 163 of file Agent.h.
References m_neighbours.
void Agent::setPosition (ngl::Vec4 _pos) inline
Definition at line 160 of file Agent.h.
References m_transformation.
void Agent::setPreviousPos (ngl::Vec4 _pos) inline
Definition at line 161 of file Agent.h.
References m_previousTransform.
void Agent::setState (std::string _state) inline
Definition at line 165 of file Agent.h.
References m_state.
static void Agent::setStep (float _step) inline static
Definition at line 151 of file Agent.h.
References s_step.
void Agent::setVelocity (ngl::Vec4 _vel) inline
Definition at line 162 of file Agent.h.
References m_velocity.
void Agent::setVisionRadius (float _visionRadius) inline
Definition at line 159 of file Agent.h.
References m_visionRadius.
Member Data Documentation
int Agent::m_agentID private
The unique agent ID which differentiates it from any other.
Definition at line 69 of file Agent.h.
std::map<std::string,std::string> Agent::m_attributes private
Map which stores extra attributes to provide more information to the brain.
Definition at line 130 of file Agent.h.
std::string Agent::m_brain private
Name of the brain, which correspondes with the lua function that encapsulates the "intelligent" routine.
Definition at line 121 of file Agent.h.
float Agent::m_collisionRadius private
Radius of the agent in order to handle the collisions.
Definition at line 138 of file Agent.h.
ngl::Obj* Agent::m_dummy private
Dummy used when drawing the agent.
Definition at line 142 of file Agent.h.
ngl::Vec4 Agent::m_heading private
Current heading of the agent. It often points the same direction than the velocity, but this does not have to happen always.
Definition at line 98 of file Agent.h.
std::vector<message> Agent::m_inbox private
Vector with all the incoming messages from other agents.
Definition at line 125 of file Agent.h.
float Agent::m_mass private
The mass of the agent.
Definition at line 73 of file Agent.h.
float Agent::m_maxSpeed private
Maximum speed this agent can move with.
Definition at line 102 of file Agent.h.
float Agent::m_maxStrength private
The maximum strength the agent has in full recovery state.
Definition at line 81 of file Agent.h.
std::vector<Agent*> Agent::m_neighbours private
Vector with the current neighbours of the agent.
Definition at line 134 of file Agent.h.
ngl::Transformation Agent::m_previousTransform private
Transformation of the agent in the previous tick.
Definition at line 111 of file Agent.h.
std::string Agent::m_state private
State of the agent. Information needed for the brain in order to take decisions.
Definition at line 116 of file Agent.h.
float Agent::m_strength private
The current strength of the agent. This attribute is mutable.
Definition at line 77 of file Agent.h.
ngl::Vec4 Agent::m_totalForce private
Stores the total force applied on this agent.
Definition at line 89 of file Agent.h.
ngl::Transformation Agent::m_transformation private
Current transformation of the agent. This includes translation rotation and scale.
Definition at line 107 of file Agent.h.
ngl::Vec4 Agent::m_velocity private
Current velocity of the agent.
Definition at line 93 of file Agent.h.
float Agent::m_visionRadius private
This determines the portion of the world the agent is aware of.
Definition at line 85 of file Agent.h.
lua_State * Agent::s_luaState static private
Lua state which holds the scripted brain functions.
Definition at line 53 of file Agent.h.
int Agent::s_numberOfAgents = 0 static private
Number of the current agents, used to associate an agent identifier.
Definition at line 58 of file Agent.h.
float Agent::s_step = 0.05 static private
This controls the rate of change of the position of the agent. This attribute is very important and influences the simulation very much.
Definition at line 64 of file Agent.h.
The documentation for this class was generated from the following files:
Agent.h
Agent.cpp