Crowd Simulator: QuadraticGridCP Class Reference
QuadraticGridCP Class Reference
Specialized 2D CellPartition.
#include <QuadraticGridCP.h>
Public Member Functions
QuadraticGridCP (int _cellSize)
~QuadraticGridCP ()
void addAgent (Agent *_agent)
Add _agent to the cell partition.
void addAgents (const std::vector< Agent * > &_agents)
Add _agents to the cell partition.
void updateCells (const std::vector< Agent * > &_agents)
Update location of _agents in the cell partition.
void updateNeighbours (const std::vector< Agent * > &_agents)
Update the neighbours of _agents.
void rearrangePartition (int _cellSize, const std::vector< Agent * > &_agents)
Recalculate the complete cell partition. This must be done when the cellSize is changed.
void printCells () const
Print information about the cells.
void clear ()
Remove all the agents from the cells.
Public Member Functions inherited from CellPartition
CellPartition (int _cellSize)
virtual ~CellPartition ()
int getCellSize () const
Private Member Functions
std::pair< int, int > cell (ngl::Vec4 _position) const
Calculates the index of the corresponding cell from a position.
void findAgentsInCells (ngl::Vec3 _leftDownCornerBox, ngl::Vec3 _rightUpCornerBox, std::vector< Agent * > &_agentsInCells)
Find the agents in the cells which contains a squared surface.
void findNeighboursInAgents (const Agent *_agent, const std::vector< Agent * > &_agentsInCells, std::vector< Agent * > &_neighbours) const
Find the neighbours of _agent from the agents in a group of cells.
Private Attributes
std::map< std::pair< int, int >
, std::list< Agent * > > m_cells
Map which store the cell indexes and the agent in each one.
Additional Inherited Members
Protected Attributes inherited from CellPartition
int m_cellSize
Size of the cell.
Detailed Description
Specialized 2D CellPartition.
Definition at line 16 of file QuadraticGridCP.h.
Constructor & Destructor Documentation
QuadraticGridCP::QuadraticGridCP (int _cellSize) inline
Definition at line 38 of file QuadraticGridCP.h.
QuadraticGridCP::~QuadraticGridCP () inline
Definition at line 39 of file QuadraticGridCP.h.
Member Function Documentation
void QuadraticGridCP::addAgent (Agent * _agent) virtual
Add _agent to the cell partition.
Implements CellPartition.
Definition at line 13 of file QuadraticGridCP.cpp.
References cell(), Agent::getPosition(), and m_cells.
void QuadraticGridCP::addAgents (const std::vector< Agent * > & _agents) virtual
Add _agents to the cell partition.
Implements CellPartition.
Definition at line 18 of file QuadraticGridCP.cpp.
References cell(), Agent::getPosition(), and m_cells.
std::pair< int, int > QuadraticGridCP::cell (ngl::Vec4 _position) const inline private
Calculates the index of the corresponding cell from a position.
This is the way of indexing (i-1)k < n < ik => n belongs to k
Definition at line 3 of file QuadraticGridCP.cpp.
References CellPartition::m_cellSize.
void QuadraticGridCP::clear () inline virtual
Remove all the agents from the cells.
Implements CellPartition.
Definition at line 68 of file QuadraticGridCP.h.
References m_cells.
void QuadraticGridCP::findAgentsInCells (ngl::Vec3 _leftDownCornerBox, ngl::Vec3 _rightUpCornerBox, std::vector< Agent * > & _agentsInCells) private
Find the agents in the cells which contains a squared surface.
Definition at line 150 of file QuadraticGridCP.cpp.
References cell(), and m_cells.
void QuadraticGridCP::findNeighboursInAgents (const Agent * _agent, const std::vector< Agent * > & _agentsInCells, std::vector< Agent * > & _neighbours) const private
Find the neighbours of _agent from the agents in a group of cells.
Take care with who was the neighbour of who... Previously, it was an important bug here because it was used the visionRadious of the neighbour(agent) instead of the _agent
Definition at line 170 of file QuadraticGridCP.cpp.
References Agent::distance(), and Agent::getVisionRadius().
void QuadraticGridCP::printCells () const virtual
Print information about the cells.
Implements CellPartition.
Definition at line 53 of file QuadraticGridCP.cpp.
References m_cells.
void QuadraticGridCP::rearrangePartition (int _cellSize, const std::vector< Agent * > & _agents) virtual
Recalculate the complete cell partition. This must be done when the cellSize is changed.
Implements CellPartition.
Definition at line 191 of file QuadraticGridCP.cpp.
References addAgents(), m_cells, and CellPartition::m_cellSize.
void QuadraticGridCP::updateCells (const std::vector< Agent * > & _agents) virtual
Update location of _agents in the cell partition.
Implements CellPartition.
Definition at line 30 of file QuadraticGridCP.cpp.
References cell(), Agent::getPosition(), Agent::getPreviousPos(), and m_cells.
void QuadraticGridCP::updateNeighbours (const std::vector< Agent * > & _agents) virtual
Update the neighbours of _agents.
Implements CellPartition.
Definition at line 73 of file QuadraticGridCP.cpp.
References findAgentsInCells(), findNeighboursInAgents(), Agent::getPosition(), Agent::getVisionRadius(), CellPartition::m_cellSize, and Agent::setNeighbours().
Member Data Documentation
std::map<std::pair<int,int>,std::list<Agent*> > QuadraticGridCP::m_cells private
Map which store the cell indexes and the agent in each one.
Definition at line 23 of file QuadraticGridCP.h.
The documentation for this class was generated from the following files:
QuadraticGridCP.h
QuadraticGridCP.cpp